@base = http://localhost:8080/api

#### Sign Up
POST {{base}}/auth/signup
Content-Type: application/json

{
    "email": "tom@email.com",
    "password": "password",
    "imageUrl": "/images/tom.png"
}

#### Obtain Token
# @name login
POST {{base}}/auth/login
Content-Type: application/json

{
    "userName": "tom@email.com",
    "password": "password"
}

#### Register
# @name register
POST {{base}}/auth/register
Content-Type: application/json
Authorization: Bearer {{login.response.body.registrationToken}}

{
    "firstName": "tom",
    "lastName": "rtom",
    "dob": "0002-02-22"
}

#### Logout
POST {{base}}/auth/logout
Authorization: Bearer {{register.response.body.authToken}}
Content-Type: application/json

#### Refresh Token
# @name refresh
POST {{base}}/auth/refresh
Authorization: Bearer {{register.response.body.authToken}}
Content-Type: application/json

{
    "token": {{register.response.body.refreshToken}},
}